name: Continuous Integration

on:
  push:
    branches:
      - feature/exercicio3
  pull_request:
    branches:
      - develop

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Navigate to the src directory and build
        run: |
          npx tsc -d
          cp -r ./* ./dist
          echo "dentro de src: "
          ls
          rm app.ts
          cd dist
          echo "dentro de dist: "
          ls
          echo "tamanho de dist: "
          du -sh
          echo "links fisicos na dist: "
          find . -type l

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: dist
          token: ${{ secrets.DEPLOY_KEY }}
